### ISSUE TITLE
Error while importing the class - NameError: name 'np' is not defined

### ISSUE THREAD

**Issue by jamespaultg** [Baukebrenninkmeijer/Table_Evaluator#5]
I am trying to use your package ‘table_evaluator’, but getting an error while importing the class. Any idea what is going wrong with the import of numpy? Appreciate your inputs. Thanks.

`!pip install table_evaluator`
`from table_evaluator import *   `

**Comment by Baukebrenninkmeijer** [comment]
Cause by incompatibility with new dython version. Code is now updated. Tests not yet, so new version is not yet pushed.

**Comment by Baukebrenninkmeijer** [comment]
Should be fixed in #7. Please check. New version is up on Pypi
